global:
  scrape_interval: 15s        # Fréquence de collecte des métriques
  evaluation_interval: 15s    # Fréquence d'évaluation des règles

scrape_configs:
  - job_name: 'spring-boot-app'           # Nom de la tâche affiché dans Grafana
    metrics_path: '/actuator/prometheus'  # Chemin exposé par Spring Boot
    static_configs:
      - targets: ['13.37.228.147:8080', 'host.docker.internal:8080'] #VM EC2 + machine locale
        labels:
          instance: spring-app-instance-1
